### ISSUE TITLE
Locking down Trivy operator RBAC

### ISSUE THREAD

**Issue by mtcolman** [aquasecurity/trivy-operator#187]
Hi, I've just been reviewing the [rbac.yaml](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/static/02-trivy-operator.rbac.yaml) and I'm wondering if it's overly permissive given that a clusterRole and clusterRoleBinding are used?

I've seen `create`, `update` and `delete` actions are available on numerous resources and the binding is cluster wide (i.e. all namespaces), permission examples include:
  - Configmaps
  - secrets
  - serviceaccounts
  - Events
  - Jobs

Which I believe means I could copy secrets from one namespace to another and spin up jobs with malicious containers within. Could this instead be split into "get, list, watch" = all namespaces and "create, update, delete" namespaced to specific namespace it is required for? Or does it really need to be able to create the above in any/all namespaces in cluster?

Matt

**Comment by erikgb** [comment]
@mtcolman Thanks for registering this issue! I agree that the ClusterRole assigned to the trivy-operator ServiceAccount has far too elevated permissions to cluster-wide resources, and should be reviewed and adjusted. I cannot image that the trivy-controllers actually need all these permissions, so I suspect this to be "leftovers" after removing `ClusterVulnerabilityReport` in https://github.com/aquasecurity/trivy-operator/pull/123. @josedonizetti @chen-keinan is this something you could look into?

**Comment by chen-keinan** [comment]
@mtcolman  thank you for pointing out this concern.
I do see that we can improve permission grant to trivy-operator.

1. create a new Role (namespace scope)  for `create` , `update` and `delete` verbs and remove it from ClusterRole for the following
    - ConfigMaps
    - Secrets
    - ServiceAccount

2. keep  the following resources (create / update / delete )in ClusterRole as trivy-operator need it for it scanning capabilities
   - Jobs `(trivy-operator have a feature where it invoke a scan job on a different namespace )`
   
3. still to review if can changed grant on the permission can change
   - Events

**Comment by erikgb** [comment]
I can work on this.

/assign

**Comment by erikgb** [comment]
@chen-keinan @josedonizetti This is far more complicated than I imagined! My analyze so far, indicates that the current operator RBAC-setup isn't far from what is needed to support all features in trivy-operator for all operator setups (union of all requirements).

I have created a draft PR (https://github.com/aquasecurity/trivy-operator/pull/215) to document my findings. I have added controller-gen rbac markers in the code - to show where the RBAC requirements are originating from, and update the Makefile to generate ClusterRole/Role based on the markers. Note: There might be bugs in my initial scan....

What affects the RBAC most, seems to be which features in trivy-operator you actually use, which makes sense. But the union of all features forces us to give the operator quite elevated permissions.... In addition, [support for private registries](https://github.com/aquasecurity/trivy-operator/blob/main/docs/vulnerability-scanning/private-registries.md) makes this really bad IMO - since that forces us to grant cluster-wide permissions to secrets and serviceaccounts. These permissions must be cluster-wide, since the user can choose to run the scan jobs in the operator or workload namespaces....

I am not sure how to address this? Suggestions?

**Comment by chen-keinan** [comment]
- Running the scan job on the `trivy-system` namespace with private registries do require access to workload secret / service account   can't be avoided unless we find another way to get the image pull secrets in a dynamic way.

- Running  scan job on the workload namespace is less permissive , as we do not have access directly to secrets/service account, scan job access to secret/service account its leverage by namespace inheritance.

We do aware to high permission requirements in this matter however the features itself are important enough for the requirements to be accepted.  
anyway, we are open for suggestion / improvements for reducing the requirements and still meet the functionality.
