### ISSUE TITLE
feat: Trivy Flag Updates

### ISSUE THREAD

**Issue by Hacks4Snacks** [aquasecurity/trivy-operator#2217]
Trivy has moved to deprecate the "slow" flag in favor of "parallel", as such we should start transitioning away from the "slow" flag. However, there is a question of backwards compatibility. For the PR that introduces "parallel", should "slow" be retained as a configuration option that maps to a default "parallel" setting or should "slow" be stripped completely?

Additionally, in the upcoming v0.55.0 Trivy will be introducing the "detection-priority" flag (reference: https://github.com/aquasecurity/trivy/discussions/7198) that we should expose as configurable in the Helm chart.

**Comment by itaysk** [comment]
sorry for missing this, we take this kind of feedback under Discussions not Issues. Generally we have a process of announcing deprecation, allowing transitioning period, and supporting backwards compatibility for a while (in the case of flags using aliases). sometimes there are exceptions to this process due to legitimate reasons, and sometimes there are mistakes. but FTR, you are right.
