### ISSUE TITLE
cache controller-gen and other binaries in bin folder

### ISSUE THREAD

**Issue by padlar** [aquasecurity/trivy-operator#231]
It might be better if GHA could cache the files in the bin folder. If not, this will have to be downloaded on each CI run. Not sure how easy that is to set up?

_Originally posted by @erikgb in https://github.com/aquasecurity/trivy-operator/pull/209#discussion_r910919299_

**Comment by chen-keinan** [comment]
@padlar please elaborate on process. what is the problem we are trying to solve and more details on the solution

**Comment by erikgb** [comment]
@chen-keinan I can clarify a bit:

This issue was created from a comment from me when reviewing https://github.com/aquasecurity/trivy-operator/pull/209. In this PR we install controller-gen to a local bin-folder. There should be no need to redo that every time, as the binary will remain the same until we change the version. So the suggestion was to cache the bin-folder contents in CI (GHA), as we do here: https://github.com/aquasecurity/trivy-operator/blob/main/.github/workflows/build.yaml#L52-L58

**Comment by chen-keinan** [comment]
Not require anymore.
