### ISSUE TITLE
Unable to set trivy.command via Helm chart

### ISSUE THREAD

**Issue by erikgb** [aquasecurity/trivy-operator#379]
**What steps did you take and what happened:**

I want to try the [filesystem mode](https://aquasecurity.github.io/trivy/v0.30.1/docs/references/cli/fs/) of trivy, and I know from looking at the code in trivy-operator that it should be supported by the operator. But I cannot find a way to configure it using the Helm chart.

**What did you expect to happen:**

I can configure `trivy.command` via the Helm chart.

**Anything else you would like to add:**

This should be an easy fix, but I am unsure if we should use the term `command` in the Helm chart values. I consider this term more like CLI-wording, but at the same time it will be a bit confusing to alias names. WDYT @chen-keinan?

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.1.5

**Comment by chen-keinan** [comment]
@erikgb you should be able to configure `fs mode` by setting it in `trivy-operator-trivy-config` with `trivy.command: filesystem`

**Comment by erikgb** [comment]
> @erikgb you should be able to configure `fs mode` by setting it in `trivy-operator-trivy-config` with `trivy.command: filesystem`

@chen-keinan I know, but not available through the Helm chart, ref. the bug title. Also asked on Slack: https://aquasecurity.slack.com/archives/C03L2H45L3H/p1658393524973549?thread_ts=1657901726.745519&cid=C03L2H45L3H

**Comment by chen-keinan** [comment]
I see but this is a trivy param, not sure it should be part of helm , we are working now for introducing `trivy.config.yaml` to give all trivy options included in one yaml structure which will be passed to trivy job via configmap. so we could have all options in once place

**Comment by josedonizetti** [comment]
@chen-keinan Think this one makes sense. We currently allow users for example to change the trivy mode on the helm installation, so it would make sense to allow to change the command too, even if later we move to the configmap.

https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L126

**Comment by chen-keinan** [comment]
> @chen-keinan Think this one makes sense. We currently allow users for example to change the trivy mode on the helm installation, so it would make sense to allow to change the command too, even if later we move to the configmap.
> 
> https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L126

Note sure about is as `Mode` is not a trivy param while `fs` is , therefore I think its place is with the params

**Comment by josedonizetti** [comment]
> Note sure about it as `Mode` is not a trivy param while `fs` is , therefore I think its place is with the params , we can externalised many of trivy params to `helm` not sure its right

Gotcha. Interesting semantics. I see them as the same because, `mode` control if you use a trivy flag `--server` or not, on the operator mode decides if you get `getPodSpecForStandaloneMode` or `getPodSpecForClientServerMode`. While command control if you get the two options mentioned (depending on mode) or`getPodSpecForStandaloneFSMode`. 
At least for me they feel very similar to each other, one controlling a command, and another a flag. 

And thinking about it `mode` was controlling a command not to long ago, because the way trivy would access a server before was `trivy client` and not `trivy image`

**Comment by josedonizetti** [comment]
@chen-keinan Thinking about it, and maybe we should not have `command` at all, because we don't support all trivy commands, we support different ways of running trivy. Maybe `mode` should support 3 options `Standalone`, `ClientServer` and `Filesystem`, each configure trivy to run on a different way. WDYT?

**Comment by chen-keinan** [comment]
Not sure,  it sound wired , Standalone or server mean where the Vuln DB is located (locally or remote) , Filesystem is scanning param , so there could be many combination as `Standalone Image` , `Standalone Fs` , `Server Image` and `Server fs` .IMO how trivy  operate,  FS or Image its Trivy config and should not be as part of helm chart .

**Comment by chen-keinan** [comment]
@josedonizetti Thinking  about it again  , I agree with you that this `FS` param can be and should exposed via helm chart.
