### ISSUE TITLE
Choose to Install CRDs

### ISSUE THREAD

**Issue by kek112** [aquasecurity/trivy-operator#723]
Hello, 

i would like to request the possibility to install or don't install CRDs. 
Similar to this [External Secrets Operator](https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml#L13), it would be nice to choose if the CRD are installed or not.

**Comment by chen-keinan** [comment]
@kek112 sound reasonable , you can pick it up if you have time

**Comment by rlex** [comment]
Not sure if i need to create another issue...
Stumbled upon issue where trivy-operator would not start after update.
Turns out new CRD was added (https://github.com/aquasecurity/trivy-operator/blob/main/deploy/crd/aquasecurity.github.io_clusterinfraassessmentreports.yaml)

This isn't mentioned anything in chart readme (and helm upgrade, AFAIK, doesn't handle CRD updates). A i missing something?

**Comment by chen-keinan** [comment]
> Not sure if i need to create another issue... Stumbled upon issue where trivy-operator would not start after update. Turns out new CRD was added (https://github.com/aquasecurity/trivy-operator/blob/main/deploy/crd/aquasecurity.github.io_clusterinfraassessmentreports.yaml)
> 
> This isn't mentioned anything in chart readme (and helm upgrade, AFAIK, doesn't handle CRD updates). A i missing something?

@rlex could you please add more detail what led to `trivy-operator would not start after update...` ?

**Comment by rlex** [comment]
@chen-keinan lack of file i linked. Helm upgrade won't bump CRDs, and operator will fail to start due to absence of said CRD.

**Comment by chen-keinan** [comment]
@kek112 if you run `helm install --skip-crds ...` will it solve you issue. ?

**Comment by chen-keinan** [comment]
no fixed is required here
