### ISSUE TITLE
expose findings as prometheus metrics

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/trivy-operator#78]
create a prometheus exporter that exposes the results or trivy-operator as prometheus metrics.
For example, vulnerabilities as metrics.

TBD: spec how results map to metrics and labels

**Comment by erikgb** [comment]
What kind of prometheus support are we looking for with this issue? Do we want:

1. Custom operator metrics, in addition to the ones provided by controller-runtime metrics?
2. Produce metrics from VulnerabilityReport, ConfigAuditReport CRDs? Ref. https://github.com/aquasecurity/trivy-operator/discussions/88
3. Both of the above?

IMO the answer is 3. The reason I ask, is that I might have an interesting contribution to this project if you think it might be a good idea. Somehow, we were not aware of this operator, nor it's predecessor starboard, until a few days ago. Still we have been using Trivy to scan images in our pipelines for quite some time. 😊

Scanning container images for workloads running in our clusters have been something we wanted to do for a long time. And struggling to find any good open source alternatives, that fulfilled our requirements, we started developing an in-house operator a couple of months ago. It works pretty well already, and we were supposed to put the operator into production this week. But due to some performance issues in the API towards our external image scanner (JFrog X-ray) it was postponed.

But then we discovered this operator! And (surprisingly) the design is somehow quite similar to what we have built - except for some obvious differences like internal/external image scanning. 👍 

Back to the issue service; metrics. We had a clear requirement for providing prometheus metrics for workload image scan results, and spent quite some time finding a fully working solution that scales and produces correct results. Our first approach was to add the metrics to the registry provided by controller-runtime to the operator. This solution had as least two issues:

1. The memory consumed by the controller container increased significantly because of the rich metrics stored in the internal registry.
2. Issues clearing out obsolete metrics without restarting the controller. The latter is still an [open issue](https://github.com/giantswarm/starboard-exporter/issues/48) in starboard-exporter, and pretty hard to solve - mainly because prometheus require complete matching labels to delete anything from the registry.

We managed to fix 2 by adding finalizers to our CRDs, but finalizers isn't something you want unless you really need it.

Looking for alternatives, we discussed providing the metrics from a separate workload, like starboard-exporter does. But it appeared less attractive, since this new workload would need to access the same API resources as already available in the operator cache.

What we ended up doing, that works very well, was to create a [custom prometheus collector](https://prometheus.io/docs/instrumenting/writing_exporters/#collectors) that converts the API resources to metrics when the metrics endpoint is scraped. All relevant API resources are already available in the controller-manager cache, so this seems to scale well and do not waste cluster resources. In order to avoid duplicate metrics when running the controller with leader election enabled and replicas > 1, we had to make the collector registration leader election aware. But fortunately controller-runtime has good support for this use case....

WDYT? Do you want me to create a PR with what we have done, tailored for trivy-operator?

**Comment by erikgb** [comment]
I've now created a draft PR to show how this can be done: https://github.com/aquasecurity/trivy-operator/pull/96/files

**Comment by mavo86** [comment]
Thanks I will do is so.
